services:
  - type: web
    name: ai-cooking-app-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-production.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
